baseurl = "/"
# baseURL = 'https://eustomaqua.github.io'
languageCode = 'en-us'
paginate = "20" # Number of posts per page
title = 'eustomaqua'
# theme = "mainroad" # ["hugo-notice", 'mainroad']
theme = "dpsg" # "puppet" # "stack"
# theme = ["hugo-notice", "mainroad"]
## theme = 'next'
disqusShortname = "" # Enable comments by entering your Disqus shortname
googleAnalytics = "" # Enable Google Analytics by entering your tracking id

[Author]
  name = "Aqua Eustoma"
  bio = "You're welcome to leave me comments via [email](mailto:yjbian92@hotmail.com)"
  avatar = "img/EustomaAqua.png"

[Params]
  description = "Once upon a time...."
  opengraph = true
  twitter_cards = false
  readmore = true # Show "Read more" button in list if true
  authorbox = true
  pager = true
  post_meta = ["date", "categories", "translations"] # Order of post meta information
  mainSections = ["post", "docs", "blog", "news"]
  menu = ["main", "side", "footer"]

  toc = true # enableTOC = true
  comment = true
  livereUID = "MTAyMC80OTYwMS8yNjA5Mg"
  moreMeta = true # 字数统计和预计时间,来必力评论
  busuanzi = true
  page_view_conter = true
  hasCJKLanguage = true
  reading_progress = true
  # pygmentsUseClasses = true
  ## PygmentsCodeFences = true
  ## PygmentsCodefencesGuessSyntax = true
  ## PygmentsOptions = "linenos=table"

#[markup.highlight]
#  codeFences = true
#  guessSyntax = false # true
#  h1_Lines = ""
#  lineNoStart = 1
#  lineNos = true
#  lineNumbersInTable = false
#  noClasses = true
#  # style = "github"
#  tabWidth = 2 # 4
[markup.tableOfContents]
  endLevel = 2 # 4
  startLevel = 1

[Params.style.vars]
  # highlightColor = "#1BEAA3" # Override highlight color
  highlightColor = "#10C486"

  # Override font-family sets
  # Take care of different quotes OR escaping symbols in these params if necessary
  fontFamilyPrimary = "'Open Sans', Helvetica, Arial, sans-serif"
  # Secondary font-family set responsible for pre, code, kbd, and samp tags font
  fontFamilySecondary = "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace"

[Params.logo]
  title = "Aqua Eustoma"
  subtitle = "Once upon a time...."
  # image = "img/EustomaAqua.png"

[Params.thumbnail]
  visibility = ["list", "post"] # Control thumbnail visibility
  # src = "img/EustomaAqua.png"
  # title = "Aqua Eustoma"

[Params.sidebar]
  home = "right"  # Configure layout for home page
  list = "left"   # Configure layout for list pages
  single = true   # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["search", "recent", "categories", "taglist", "social", "languages"]
  b2t = true # 返回顶部按钮
  scrollpercent = true # 返回顶部按钮的百分比

[Params.widgets]
  recent_num = 4 # Set the number of articles in the "Recent articles" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget
  categories_counter = false
[Params.widgets.social]
  # email = "yjbian92@hotmail.com" # "yjbian@mail.ustc.edu.cn"
  github = "eustomaqua"
# [[Params.widgets.social.custom]]
#   title = "Youtube"
#   url = "https://youtube.com/user/username"
#   icon = "youtube.svg"

[Params.math]
  enable = true
